### ISSUE TITLE
I don't think it's okay to make this public

### ISSUE THREAD

**Issue by RyouYoo** [stavlor/Shadow-Shortcuts#110]
Hi,
Sorry, but I don't think you should make this public for all, I tried to contact the security team but I think there are no security team.
Anyway, that's all.
Good luck.

**Comment by stavlor** [comment]
Firstly, this is a community built bot designed by the Discord Moderation team. If you have a security issue with the bot feel free to e-mail your issues/concern to stavlor@stavlor.net note that I do not work for Blade Group/Shadow.

**Comment by RyouYoo** [comment]
emm, I'm just saying
