### ISSUE TITLE
Add vhdx and ntfs command

### ISSUE THREAD

**Issue by justathoughtor2** [stavlor/Shadow-Shortcuts#13]
Command should include a link to https://www.windowscentral.com/how-create-and-set-vhdx-or-vhd-windows-10 and explanation for use case of this action.

**Comment by LEQUI000** [comment]
Should also add the Relevant Reddit Thread as well
https://www.reddit.com/r/ShadowPC/comments/h0pifp/xbox_game_pass_and_ntfs_error_workaround/

**Comment by justathoughtor2** [comment]
Sounds good. Will add soon.

**Comment by LEQUI000** [comment]
reopened to add errata
Note: You may have to change the location within Windows settings, put in the Windows search "Storage Settings" then Change where new content is saved > New apps will save to.

Then within the Xbox Beta app go to Settings > General > Drive Selection. If not changed, change it.
