### ISSUE TITLE
add events to #bot-users or #bot-logs for Code Approvers

### ISSUE THREAD

**Issue by LEQUI000** [stavlor/Shadow-Shortcuts#46]
Pull Requests for approval should ping Code Approvers
Issues/Tickets should ping Code Approvers
Merging approved should ping Code Approvers

**Comment by LEQUI000** [comment]
Pull Requests for approval should ping Code Approvers

**Comment by LEQUI000** [comment]
user (username) has made pull request ID: #-- to master from (branch), approval requested @code approvers

**Comment by stavlor** [comment]
WIP.
