### ISSUE TITLE
Stats (Shadow Quick Menu)

### ISSUE THREAD

**Issue by LEQUI000** [stavlor/Shadow-Shortcuts#49]
## Short description (Briefly explain the project)
Update the Stats command to move from the Control Panel to Quick Menu
## Reason (Who would this help?)
Control Panel is depreciated
## Invoking commands and alias
\stats
## Expected result (What the output should be)
The Stats page in the Shadow Quick Menu can provide useful troubleshooting information (IPS, Bandwidth, Ping and Packet Loss) to access it please this, while using Shadow, open your Quick Menu (Windows/Command - Alt - O) and take a screenshot of the Stats monitor?
## Is your feature request related to a problem? Please describe. (optional)

```

**Comment by LEQUI000** [comment]
I need @stavlor to upload new assets to bot rexford for this change

**Comment by stavlor** [comment]
do you have the new assets?

**Comment by LEQUI000** [comment]
To open the Quick Menu, log into the Shadow launcher, then Start Shadow.

Once Shadow starts, click the Shadow logo Quick_Menu_Logo.png located at the top of the screen, or press the Quick Menu shortcut:

   - :WindowsShadow:/⌘ + Alt + O = Toggle Quick menu

The Quick Menu is only available on Windows and macOS applications. Linux, the Shadow Ghost, and the Shadow Box will receive an update with the Quick Menu in the future.

**Comment by LEQUI000** [comment]
Actually not sure if we want an image.
![image](https://user-images.githubusercontent.com/26169690/88868314-78042c00-d1d5-11ea-8669-1d8de80ab5c4.png)
