### ISSUE TITLE
Limited Slowmode for Bot Users

### ISSUE THREAD

**Issue by allykatz** [stavlor/Shadow-Shortcuts#51]
Having bot users able to put a 15 second, 20 second, 30 second or 45 second slowmode for extreme situations 

## Reason (Who would this help?)
This would help bot users moderate chat when mods and staff are busy at night or off hours
It would make a bookmark in the log with a reason why we envoked slowmode 

## Invoking commands and alias
\botsm [time] [reason for log]
## Expected result (What the output should be)
Bot increases slowmode

```

**Comment by allykatz** [comment]
A command time limit would be helpful. Only allows the command to be used once every 10 minutes

**Comment by stavlor** [comment]
Note that even at 10 minutes we are limited at the gateway level to calls even tighter that the gateway will not hesitate to ratelimit  us if we start edging near limits and when they ratelimit its not for seconds or minutes its generally hours/days Modify Channel
PATCH/channels/{channel.id} is called everytime slowmode is edited that has a quite tight limit before rate limiting occurs literally slowmode isn't something thats intended as a on/off its set it and then turn it off a few hours later

**Comment by stavlor** [comment]
Implemented in #94 and #95
