### ISSUE TITLE
copypasta

### ISSUE THREAD

**Issue by LilyLegend** [stavlor/Shadow-Shortcuts#54]
## Dear (addressed user),

If you could perhaps consider this optimal strategy, which could facilitate about your own reward. There exists a contraption that enables one to - with a few strokes of the fingers to depress buttons in a sequence of letters to formulate a word, and then a sentence. Which if phrased as a question, could result in an answer. I believe you know of this contraption called the computer, if - when in use with the internet, one could maneuver oneself onto a place referred to as a website; I will help you in this prospect for I know of the address: www.google.com. When you find yourself in this place, you will see a box in which you could - once again, maneuver your fingers in the correct sequence in order to arrange an assortment of questions that would result in the delivery of your much needed answer.

Sincerely, 
Your friend,
(the requester of command) 

## Is your feature request related to a problem? Please describe. (optional)

```

**Comment by LEQUI000** [comment]
Under discussion as this isn't an urgent feature
