### ISSUE TITLE
Update the help command

### ISSUE THREAD

**Issue by LEQUI000** [stavlor/Shadow-Shortcuts#55]
## Invoking commands and alias
\help
## Expected result (What the output should be)
Help should be adjusted to use the GitHub workflow to ensure requests do not get lose
## Is your feature request related to a problem? Please describe. (optional)

```

**Comment by stavlor** [comment]
First help isn't a command its a Class its a very complicated one at that.. what exactly are you trying to do?

**Comment by LEQUI000** [comment]
Maybe I didn't clarify, this is just to add the GitHub link at the top of help.
