### ISSUE TITLE
Add Linus Tech Tips video

### ISSUE THREAD

**Issue by LEQUI000** [stavlor/Shadow-Shortcuts#6]
## Request
Add Linus Tech Tips video
## Reason
Guide more users to view the technical understanding of Shadow and it's server components
## Invoking Command
ltt2 or ltt
## Expected result (what output should be)
View the Linus Tech Tips server reveal here:
<https://shdw.me/LTTVideo>
## Links to documents
N/A

**Comment by stavlor** [comment]
Probably best to simply update this as there is already a \ltt command.
async def linustechtips(self, ctx, user: typing.Optional[discord.Member] = None):

**Comment by justathoughtor2** [comment]
Good to know. Will do.
