### ISSUE TITLE
ShadOwO

### ISSUE THREAD

**Issue by justathoughtor2** [stavlor/Shadow-Shortcuts#97]
## Short description (Briefly explain the project)
uwu

## Reason (Who would this help?)
Cute Shadow is good Shadow.

## Invoking commands and alias
\shadowo
\shaduwu

## Expected result (What the output should be)
ShadOwO image

## Links or extra details
https://cdn.discordapp.com/attachments/550519535606956032/738174990855438418/shadowo.png

## Is your feature request related to a problem? Please describe. (optional)

```

**Comment by LEQUI000** [comment]
sure?

**Comment by justathoughtor2** [comment]
https://cdn.discordapp.com/attachments/550519535606956032/739318032022634566/shadowo_wallpaper.png
